package io.hpb.mapper;

import io.hpb.entity.ContractErcStandardInfo;
import io.hpb.example.ContractErcStandardInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContractErcStandardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    long countByExample(ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int deleteByExample(ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int insert(ContractErcStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int insertSelective(ContractErcStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    List<ContractErcStandardInfo> selectByExample(ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    ContractErcStandardInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContractErcStandardInfo record, @Param("example") ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContractErcStandardInfo record, @Param("example") ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContractErcStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractErcStandardInfo record);

    ContractErcStandardInfo selectByContractAddress(@Param("contractAddress") String contractAddress);


    void updateSymbolUrl(@Param("contractAddress") String contractAddress, @Param("url") String url);
}