package io.hpb.mapper;

import io.hpb.entity.ContractInfo;
import io.hpb.example.ContractInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    long countByExample(ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int deleteByExample(ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String contractAddr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int insert(ContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int insertSelective(ContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    List<ContractInfo> selectByExampleWithBLOBs(ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    List<ContractInfo> selectByExample(ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    ContractInfo selectByPrimaryKey(String contractAddr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContractInfo record, @Param("example") ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ContractInfo record, @Param("example") ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContractInfo record, @Param("example") ContractInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractInfo record);
}