package io.hpb.model;

import java.math.BigDecimal;
import java.util.Date;

public class ContractInfoModel extends BaseModel {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_info.contract_addr
     *
     * @mbg.generated
     */
    private String contractAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_info.contract_creater
     *
     * @mbg.generated
     */
    private String contractCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_info.contract_name
     *
     * @mbg.generated
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_info.contract_src
     *
     * @mbg.generated
     */
    private String contractSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_info.contract_abi
     *
     * @mbg.generated
     */
    private String contractAbi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_info.contract_bin
     *
     * @mbg.generated
     */
    private String contractBin;

    private String contractType;

    private String optimizeFlag;

    private BigDecimal balance;

    private Long txCount;

    private String verifiedStatus;

    private String dappUrl;

    private Long miscSettingRuns;

    private String hvmVersion;

    private String compilerType;

    private String compilerVersion;

    private Date createTimestamp;


    public String getContractAddr() {
        return contractAddr;
    }

    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr;
    }

    public String getContractCreater() {
        return contractCreater;
    }

    public void setContractCreater(String contractCreater) {
        this.contractCreater = contractCreater;
    }

    public String getContractName() {
        return contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public String getContractSrc() {
        return contractSrc;
    }

    public void setContractSrc(String contractSrc) {
        this.contractSrc = contractSrc;
    }

    public String getContractAbi() {
        return contractAbi;
    }

    public void setContractAbi(String contractAbi) {
        this.contractAbi = contractAbi;
    }

    public String getContractBin() {
        return contractBin;
    }

    public void setContractBin(String contractBin) {
        this.contractBin = contractBin;
    }

    public String getContractType() {
        return contractType;
    }

    public void setContractType(String contractType) {
        this.contractType = contractType;
    }

    public String getOptimizeFlag() {
        return optimizeFlag;
    }

    public void setOptimizeFlag(String optimizeFlag) {
        this.optimizeFlag = optimizeFlag;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Long getTxCount() {
        return txCount;
    }

    public void setTxCount(Long txCount) {
        this.txCount = txCount;
    }

    public String getVerifiedStatus() {
        return verifiedStatus;
    }

    public void setVerifiedStatus(String verifiedStatus) {
        this.verifiedStatus = verifiedStatus;
    }

    public String getDappUrl() {
        return dappUrl;
    }

    public void setDappUrl(String dappUrl) {
        this.dappUrl = dappUrl;
    }

    public Long getMiscSettingRuns() {
        return miscSettingRuns;
    }

    public void setMiscSettingRuns(Long miscSettingRuns) {
        this.miscSettingRuns = miscSettingRuns;
    }

    public String getHvmVersion() {
        return hvmVersion;
    }

    public void setHvmVersion(String hvmVersion) {
        this.hvmVersion = hvmVersion;
    }

    public String getCompilerType() {
        return compilerType;
    }

    public void setCompilerType(String compilerType) {
        this.compilerType = compilerType;
    }

    public String getCompilerVersion() {
        return compilerVersion;
    }

    public void setCompilerVersion(String compilerVersion) {
        this.compilerVersion = compilerVersion;
    }

    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }
}
