package io.hpb.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContractErcStandardInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public ContractErcStandardInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolIsNull() {
            addCriterion("token_symbol is null");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolIsNotNull() {
            addCriterion("token_symbol is not null");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolEqualTo(String value) {
            addCriterion("token_symbol =", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolNotEqualTo(String value) {
            addCriterion("token_symbol <>", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolGreaterThan(String value) {
            addCriterion("token_symbol >", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("token_symbol >=", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolLessThan(String value) {
            addCriterion("token_symbol <", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolLessThanOrEqualTo(String value) {
            addCriterion("token_symbol <=", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolLike(String value) {
            addCriterion("token_symbol like", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolNotLike(String value) {
            addCriterion("token_symbol not like", value, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolIn(List<String> values) {
            addCriterion("token_symbol in", values, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolNotIn(List<String> values) {
            addCriterion("token_symbol not in", values, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolBetween(String value1, String value2) {
            addCriterion("token_symbol between", value1, value2, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolNotBetween(String value1, String value2) {
            addCriterion("token_symbol not between", value1, value2, "tokenSymbol");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlIsNull() {
            addCriterion("token_symbol_image_url is null");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlIsNotNull() {
            addCriterion("token_symbol_image_url is not null");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlEqualTo(String value) {
            addCriterion("token_symbol_image_url =", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlNotEqualTo(String value) {
            addCriterion("token_symbol_image_url <>", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlGreaterThan(String value) {
            addCriterion("token_symbol_image_url >", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("token_symbol_image_url >=", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlLessThan(String value) {
            addCriterion("token_symbol_image_url <", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlLessThanOrEqualTo(String value) {
            addCriterion("token_symbol_image_url <=", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlLike(String value) {
            addCriterion("token_symbol_image_url like", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlNotLike(String value) {
            addCriterion("token_symbol_image_url not like", value, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlIn(List<String> values) {
            addCriterion("token_symbol_image_url in", values, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlNotIn(List<String> values) {
            addCriterion("token_symbol_image_url not in", values, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlBetween(String value1, String value2) {
            addCriterion("token_symbol_image_url between", value1, value2, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenSymbolImageUrlNotBetween(String value1, String value2) {
            addCriterion("token_symbol_image_url not between", value1, value2, "tokenSymbolImageUrl");
            return (Criteria) this;
        }

        public Criteria andTokenNameIsNull() {
            addCriterion("token_name is null");
            return (Criteria) this;
        }

        public Criteria andTokenNameIsNotNull() {
            addCriterion("token_name is not null");
            return (Criteria) this;
        }

        public Criteria andTokenNameEqualTo(String value) {
            addCriterion("token_name =", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameNotEqualTo(String value) {
            addCriterion("token_name <>", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameGreaterThan(String value) {
            addCriterion("token_name >", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameGreaterThanOrEqualTo(String value) {
            addCriterion("token_name >=", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameLessThan(String value) {
            addCriterion("token_name <", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameLessThanOrEqualTo(String value) {
            addCriterion("token_name <=", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameLike(String value) {
            addCriterion("token_name like", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameNotLike(String value) {
            addCriterion("token_name not like", value, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameIn(List<String> values) {
            addCriterion("token_name in", values, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameNotIn(List<String> values) {
            addCriterion("token_name not in", values, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameBetween(String value1, String value2) {
            addCriterion("token_name between", value1, value2, "tokenName");
            return (Criteria) this;
        }

        public Criteria andTokenNameNotBetween(String value1, String value2) {
            addCriterion("token_name not between", value1, value2, "tokenName");
            return (Criteria) this;
        }

        public Criteria andDecimalsIsNull() {
            addCriterion("decimals is null");
            return (Criteria) this;
        }

        public Criteria andDecimalsIsNotNull() {
            addCriterion("decimals is not null");
            return (Criteria) this;
        }

        public Criteria andDecimalsEqualTo(Long value) {
            addCriterion("decimals =", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsNotEqualTo(Long value) {
            addCriterion("decimals <>", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsGreaterThan(Long value) {
            addCriterion("decimals >", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsGreaterThanOrEqualTo(Long value) {
            addCriterion("decimals >=", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsLessThan(Long value) {
            addCriterion("decimals <", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsLessThanOrEqualTo(Long value) {
            addCriterion("decimals <=", value, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsIn(List<Long> values) {
            addCriterion("decimals in", values, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsNotIn(List<Long> values) {
            addCriterion("decimals not in", values, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsBetween(Long value1, Long value2) {
            addCriterion("decimals between", value1, value2, "decimals");
            return (Criteria) this;
        }

        public Criteria andDecimalsNotBetween(Long value1, Long value2) {
            addCriterion("decimals not between", value1, value2, "decimals");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashIsNull() {
            addCriterion("deploy_tx_hash is null");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashIsNotNull() {
            addCriterion("deploy_tx_hash is not null");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashEqualTo(String value) {
            addCriterion("deploy_tx_hash =", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashNotEqualTo(String value) {
            addCriterion("deploy_tx_hash <>", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashGreaterThan(String value) {
            addCriterion("deploy_tx_hash >", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashGreaterThanOrEqualTo(String value) {
            addCriterion("deploy_tx_hash >=", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashLessThan(String value) {
            addCriterion("deploy_tx_hash <", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashLessThanOrEqualTo(String value) {
            addCriterion("deploy_tx_hash <=", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashLike(String value) {
            addCriterion("deploy_tx_hash like", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashNotLike(String value) {
            addCriterion("deploy_tx_hash not like", value, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashIn(List<String> values) {
            addCriterion("deploy_tx_hash in", values, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashNotIn(List<String> values) {
            addCriterion("deploy_tx_hash not in", values, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashBetween(String value1, String value2) {
            addCriterion("deploy_tx_hash between", value1, value2, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andDeployTxHashNotBetween(String value1, String value2) {
            addCriterion("deploy_tx_hash not between", value1, value2, "deployTxHash");
            return (Criteria) this;
        }

        public Criteria andContractCreaterIsNull() {
            addCriterion("contract_creater is null");
            return (Criteria) this;
        }

        public Criteria andContractCreaterIsNotNull() {
            addCriterion("contract_creater is not null");
            return (Criteria) this;
        }

        public Criteria andContractCreaterEqualTo(String value) {
            addCriterion("contract_creater =", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterNotEqualTo(String value) {
            addCriterion("contract_creater <>", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterGreaterThan(String value) {
            addCriterion("contract_creater >", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("contract_creater >=", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterLessThan(String value) {
            addCriterion("contract_creater <", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterLessThanOrEqualTo(String value) {
            addCriterion("contract_creater <=", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterLike(String value) {
            addCriterion("contract_creater like", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterNotLike(String value) {
            addCriterion("contract_creater not like", value, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterIn(List<String> values) {
            addCriterion("contract_creater in", values, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterNotIn(List<String> values) {
            addCriterion("contract_creater not in", values, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterBetween(String value1, String value2) {
            addCriterion("contract_creater between", value1, value2, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractCreaterNotBetween(String value1, String value2) {
            addCriterion("contract_creater not between", value1, value2, "contractCreater");
            return (Criteria) this;
        }

        public Criteria andContractAddressIsNull() {
            addCriterion("contract_address is null");
            return (Criteria) this;
        }

        public Criteria andContractAddressIsNotNull() {
            addCriterion("contract_address is not null");
            return (Criteria) this;
        }

        public Criteria andContractAddressEqualTo(String value) {
            addCriterion("contract_address =", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressNotEqualTo(String value) {
            addCriterion("contract_address <>", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressGreaterThan(String value) {
            addCriterion("contract_address >", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressGreaterThanOrEqualTo(String value) {
            addCriterion("contract_address >=", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressLessThan(String value) {
            addCriterion("contract_address <", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressLessThanOrEqualTo(String value) {
            addCriterion("contract_address <=", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressLike(String value) {
            addCriterion("contract_address like", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressNotLike(String value) {
            addCriterion("contract_address not like", value, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressIn(List<String> values) {
            addCriterion("contract_address in", values, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressNotIn(List<String> values) {
            addCriterion("contract_address not in", values, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressBetween(String value1, String value2) {
            addCriterion("contract_address between", value1, value2, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andContractAddressNotBetween(String value1, String value2) {
            addCriterion("contract_address not between", value1, value2, "contractAddress");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyIsNull() {
            addCriterion("token_total_supply is null");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyIsNotNull() {
            addCriterion("token_total_supply is not null");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyEqualTo(Long value) {
            addCriterion("token_total_supply =", value, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyNotEqualTo(Long value) {
            addCriterion("token_total_supply <>", value, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyGreaterThan(Long value) {
            addCriterion("token_total_supply >", value, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyGreaterThanOrEqualTo(Long value) {
            addCriterion("token_total_supply >=", value, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyLessThan(Long value) {
            addCriterion("token_total_supply <", value, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyLessThanOrEqualTo(Long value) {
            addCriterion("token_total_supply <=", value, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyIn(List<Long> values) {
            addCriterion("token_total_supply in", values, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyNotIn(List<Long> values) {
            addCriterion("token_total_supply not in", values, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyBetween(Long value1, Long value2) {
            addCriterion("token_total_supply between", value1, value2, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andTokenTotalSupplyNotBetween(Long value1, Long value2) {
            addCriterion("token_total_supply not between", value1, value2, "tokenTotalSupply");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("contract_type is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("contract_type is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeEqualTo(String value) {
            addCriterion("contract_type =", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotEqualTo(String value) {
            addCriterion("contract_type <>", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThan(String value) {
            addCriterion("contract_type >", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_type >=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThan(String value) {
            addCriterion("contract_type <", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(String value) {
            addCriterion("contract_type <=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLike(String value) {
            addCriterion("contract_type like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotLike(String value) {
            addCriterion("contract_type not like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeIn(List<String> values) {
            addCriterion("contract_type in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotIn(List<String> values) {
            addCriterion("contract_type not in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeBetween(String value1, String value2) {
            addCriterion("contract_type between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotBetween(String value1, String value2) {
            addCriterion("contract_type not between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusIsNull() {
            addCriterion("verified_status is null");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusIsNotNull() {
            addCriterion("verified_status is not null");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusEqualTo(String value) {
            addCriterion("verified_status =", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusNotEqualTo(String value) {
            addCriterion("verified_status <>", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusGreaterThan(String value) {
            addCriterion("verified_status >", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusGreaterThanOrEqualTo(String value) {
            addCriterion("verified_status >=", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusLessThan(String value) {
            addCriterion("verified_status <", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusLessThanOrEqualTo(String value) {
            addCriterion("verified_status <=", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusLike(String value) {
            addCriterion("verified_status like", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusNotLike(String value) {
            addCriterion("verified_status not like", value, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusIn(List<String> values) {
            addCriterion("verified_status in", values, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusNotIn(List<String> values) {
            addCriterion("verified_status not in", values, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusBetween(String value1, String value2) {
            addCriterion("verified_status between", value1, value2, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andVerifiedStatusNotBetween(String value1, String value2) {
            addCriterion("verified_status not between", value1, value2, "verifiedStatus");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andChangeRateIsNull() {
            addCriterion("change_rate is null");
            return (Criteria) this;
        }

        public Criteria andChangeRateIsNotNull() {
            addCriterion("change_rate is not null");
            return (Criteria) this;
        }

        public Criteria andChangeRateEqualTo(String value) {
            addCriterion("change_rate =", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotEqualTo(String value) {
            addCriterion("change_rate <>", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateGreaterThan(String value) {
            addCriterion("change_rate >", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateGreaterThanOrEqualTo(String value) {
            addCriterion("change_rate >=", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateLessThan(String value) {
            addCriterion("change_rate <", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateLessThanOrEqualTo(String value) {
            addCriterion("change_rate <=", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateLike(String value) {
            addCriterion("change_rate like", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotLike(String value) {
            addCriterion("change_rate not like", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateIn(List<String> values) {
            addCriterion("change_rate in", values, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotIn(List<String> values) {
            addCriterion("change_rate not in", values, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateBetween(String value1, String value2) {
            addCriterion("change_rate between", value1, value2, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotBetween(String value1, String value2) {
            addCriterion("change_rate not between", value1, value2, "changeRate");
            return (Criteria) this;
        }

        public Criteria andVolume24hIsNull() {
            addCriterion("volume_24h is null");
            return (Criteria) this;
        }

        public Criteria andVolume24hIsNotNull() {
            addCriterion("volume_24h is not null");
            return (Criteria) this;
        }

        public Criteria andVolume24hEqualTo(String value) {
            addCriterion("volume_24h =", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hNotEqualTo(String value) {
            addCriterion("volume_24h <>", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hGreaterThan(String value) {
            addCriterion("volume_24h >", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hGreaterThanOrEqualTo(String value) {
            addCriterion("volume_24h >=", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hLessThan(String value) {
            addCriterion("volume_24h <", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hLessThanOrEqualTo(String value) {
            addCriterion("volume_24h <=", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hLike(String value) {
            addCriterion("volume_24h like", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hNotLike(String value) {
            addCriterion("volume_24h not like", value, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hIn(List<String> values) {
            addCriterion("volume_24h in", values, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hNotIn(List<String> values) {
            addCriterion("volume_24h not in", values, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hBetween(String value1, String value2) {
            addCriterion("volume_24h between", value1, value2, "volume24h");
            return (Criteria) this;
        }

        public Criteria andVolume24hNotBetween(String value1, String value2) {
            addCriterion("volume_24h not between", value1, value2, "volume24h");
            return (Criteria) this;
        }

        public Criteria andMarketCapIsNull() {
            addCriterion("market_cap is null");
            return (Criteria) this;
        }

        public Criteria andMarketCapIsNotNull() {
            addCriterion("market_cap is not null");
            return (Criteria) this;
        }

        public Criteria andMarketCapEqualTo(BigDecimal value) {
            addCriterion("market_cap =", value, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapNotEqualTo(BigDecimal value) {
            addCriterion("market_cap <>", value, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapGreaterThan(BigDecimal value) {
            addCriterion("market_cap >", value, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("market_cap >=", value, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapLessThan(BigDecimal value) {
            addCriterion("market_cap <", value, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapLessThanOrEqualTo(BigDecimal value) {
            addCriterion("market_cap <=", value, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapIn(List<BigDecimal> values) {
            addCriterion("market_cap in", values, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapNotIn(List<BigDecimal> values) {
            addCriterion("market_cap not in", values, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_cap between", value1, value2, "marketCap");
            return (Criteria) this;
        }

        public Criteria andMarketCapNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_cap not between", value1, value2, "marketCap");
            return (Criteria) this;
        }

        public Criteria andHoldersIsNull() {
            addCriterion("holders is null");
            return (Criteria) this;
        }

        public Criteria andHoldersIsNotNull() {
            addCriterion("holders is not null");
            return (Criteria) this;
        }

        public Criteria andHoldersEqualTo(Integer value) {
            addCriterion("holders =", value, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersNotEqualTo(Integer value) {
            addCriterion("holders <>", value, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersGreaterThan(Integer value) {
            addCriterion("holders >", value, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersGreaterThanOrEqualTo(Integer value) {
            addCriterion("holders >=", value, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersLessThan(Integer value) {
            addCriterion("holders <", value, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersLessThanOrEqualTo(Integer value) {
            addCriterion("holders <=", value, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersIn(List<Integer> values) {
            addCriterion("holders in", values, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersNotIn(List<Integer> values) {
            addCriterion("holders not in", values, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersBetween(Integer value1, Integer value2) {
            addCriterion("holders between", value1, value2, "holders");
            return (Criteria) this;
        }

        public Criteria andHoldersNotBetween(Integer value1, Integer value2) {
            addCriterion("holders not between", value1, value2, "holders");
            return (Criteria) this;
        }

        public Criteria andTransfersNumIsNull() {
            addCriterion("transfers_num is null");
            return (Criteria) this;
        }

        public Criteria andTransfersNumIsNotNull() {
            addCriterion("transfers_num is not null");
            return (Criteria) this;
        }

        public Criteria andTransfersNumEqualTo(Integer value) {
            addCriterion("transfers_num =", value, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumNotEqualTo(Integer value) {
            addCriterion("transfers_num <>", value, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumGreaterThan(Integer value) {
            addCriterion("transfers_num >", value, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("transfers_num >=", value, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumLessThan(Integer value) {
            addCriterion("transfers_num <", value, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumLessThanOrEqualTo(Integer value) {
            addCriterion("transfers_num <=", value, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumIn(List<Integer> values) {
            addCriterion("transfers_num in", values, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumNotIn(List<Integer> values) {
            addCriterion("transfers_num not in", values, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumBetween(Integer value1, Integer value2) {
            addCriterion("transfers_num between", value1, value2, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andTransfersNumNotBetween(Integer value1, Integer value2) {
            addCriterion("transfers_num not between", value1, value2, "transfersNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}